// -*- mode: c++; -*-

/// \file bit_constants.h
/// Include file to point to pre-defined constant bit patterns
/// All the constants are designed to speed slim/unslim

// --------------------------------------------------------
// WARNING!  This file is automatically generated by
// program build_bit_constants_h.cpp  Do not edit directly.
// See that program for copyright information.
// --------------------------------------------------------

#ifndef SLIM_BIT_CONSTANTS_H
#define SLIM_BIT_CONSTANTS_H


#include <stdint.h>

typedef uint8_t Byte_t;   ///< Byte-oriented buffer for I/O
typedef uint64_t Word_t;  ///< Word-oriented type for using buffer.

extern const Word_t bitNset[64], highestNset[65], lowestNset[65];
extern const int32_t *lowestNset32bits;

#endif // SLIM_BIT_CONSTANTS_H
